In [1]:
import torch

In [13]:
#减法形式一
m=torch.rand(1,3)
n=torch.rand(2,1)
print(m-n)

#减法形式二
print(torch.sub(m,n))

#减法形式三，inplace（原地操作）
m.sub(n)
print(m)

tensor([[-0.0300, -0.6091, -0.4898],
        [ 0.3798, -0.1992, -0.0800]])
tensor([[-0.0300, -0.6091, -0.4898],
        [ 0.3798, -0.1992, -0.0800]])
tensor([[0.9395, 0.3604, 0.4797]])
